

    "Kilometers(Km)" 
    "Miles(Mi)"
    "Meters(m)"
    "Yards(yd)"
    "Centimeter(cm)"
    "Millimeter(mm)"
    "Foot(ft)"
    "Inches(in)"
    "Kilogram(Kg)"
    "Gram(g)"
    "Pound(lbs)"
    "Kilogram(Kg)"
    "Gallon(gal)"
    "Litre(l)"
    "Celcius(°C)"
    "Farhenite(°F)"
    "Kelvin(K)"
    "Seconds(s)"
    "Minutes" 
    "Hours(hrs)"

